FROM python:3.9-slim

RUN apt-get update && apt-get install -y wget openjdk-11-jre-headless && rm -rf /var/lib/apt/lists/*

# 下载Selenium Standalone Server
RUN wget -O /opt/selenium-server.jar https://github.com/SeleniumHQ/selenium/releases/download/selenium-4.15.0/selenium-server-4.15.0.jar

EXPOSE 4444

CMD ["java", "-jar", "/opt/selenium-server.jar", "hub"]
