FROM selenium/node-base:4.33.0-20250606

USER root

# 安装ADB
RUN apt-get update && apt-get install -y \
    adb \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# 复制 chromedriver
COPY chromedriver-128/chromedriver /opt/chromedriver/chromedriver
RUN chmod +x /opt/chromedriver/chromedriver

# 加入 PATH
ENV PATH="/opt/chromedriver:${PATH}"

# 复制 node 配置
COPY node-128.toml /opt/selenium/node.toml

USER seluser

# 复制配置和自定义入口脚本
COPY node-128.toml /opt/selenium/node.toml
# COPY my-entrypoint.sh /usr/local/bin/entry_point.sh


USER seluser
# ENTRYPOINT ["sh", "/usr/local/bin/entry_point.sh"]
# ENTRYPOINT ["/usr/local/bin/entry_point.sh"]

# 保持使用 entry_point.sh
# ENTRYPOINT ["/opt/bin/entry_point.sh"] 