apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chrome-nas-pvc
  namespace: selenium-grid
  labels:
    type: chrome-nas
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: chrome-nas-storage
  resources:
    requests:
      storage: 100Gi
  selector:
    matchLabels:
      type: chrome-nas



