apiVersion: v1
kind: PersistentVolume
metadata:
  name: chrome-nas-pv
  labels:
    type: chrome-nas
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: chrome-nas-storage
  nfs:
    server: 01d50c71-ijxa.cn-beijing.extreme.nas.aliyuncs.com
    path: /share
    readOnly: false
  mountOptions:
    - vers=3
    - noacl
    - nolock
    - proto=tcp
    - rsize=1048576
    - wsize=1048576
    - hard
    - timeo=600
    - retrans=2
    - noresvport


