apiVersion: v1
kind: PersistentVolume
metadata:
  name: chrome-nas-pv
  labels:
    type: chrome-nas
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: chrome-nas-storage
  nfs:
    server: 10127497f3-wws17.cn-beijing.nas.aliyuncs.com
    path: /
    readOnly: false
  mountOptions:
    - nolock
    - vers=4.0



